### Data Cleaning

Assumptions to note: Errors are considered automatic failure, while errors in a machine does not necessary mean that they will break down immediately, however it will cause bottlenecks as the machine is compromised in its functions coming slower than expected

Loaidng Datasets & 'datetime' Conversion

In [ ]:
import pandas as pd

# Load the datasets
df_telemetry = pd.read_csv('/content/PdM_telemetry.csv')
df_machines = pd.read_csv('/content/PdM_machines.csv')
df_failures = pd.read_csv('/content/PdM_failures.csv')
df_errors = pd.read_csv('/content/PdM_errors.csv')
df_maint = pd.read_csv('/content/PdM_maint.csv')

# Convert 'datetime' columns to datetime objects for merging
df_telemetry['datetime'] = pd.to_datetime(df_telemetry['datetime'])
df_failures['datetime'] = pd.to_datetime(df_failures['datetime'])
df_errors['datetime'] = pd.to_datetime(df_errors['datetime'])
df_maint['datetime'] = pd.to_datetime(df_maint['datetime'])

print("Datasets loaded and 'datetime' columns converted.")

Datasets loaded and 'datetime' columns converted.

Vieiwng Datasets

In [ ]:
df_telemetry

,datetime,machineID,volt,rotate,pressure,vibration
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847
3,2015-01-01 09:00:00,1,162.462833,346.149335,109.248561,41.122144
4,2015-01-01 10:00:00,1,157.610021,435.376873,111.886648,25.990511
...,...,...,...,...,...,...
11574,2015-04-28 11:00:00,2,177.347926,457.666367,94.690314,39.253790
11575,2015-04-28 12:00:00,2,160.741738,499.917353,102.990673,40.532562
11576,2015-04-28 13:00:00,2,188.393731,489.567225,84.165825,40.536561
11577,2015-04-28 14:00:00,2,195.562651,485.525334,102.696885,40.800559
11578,2015-04-28 15:00:00,2,177.577279,528.590666,100.944514,47.150000

In [ ]:
df_machines

    machineID   model  age
0           1  model3   18
1           2  model4    7
2           3  model3    8
3           4  model3    7
4           5  model3    2
..        ...     ...  ...
95         96  model2   10
96         97  model2   14
97         98  model2   20
98         99  model1   14
99        100  model4    5

[100 rows x 3 columns]

In [ ]:
df_failures

               datetime  machineID failure
0   2015-01-05 06:00:00          1   comp4
1   2015-03-06 06:00:00          1   comp1
2   2015-04-20 06:00:00          1   comp2
3   2015-06-19 06:00:00          1   comp4
4   2015-09-02 06:00:00          1   comp4
..                  ...        ...     ...
756 2015-11-29 06:00:00         99   comp3
757 2015-12-14 06:00:00         99   comp4
758 2015-02-12 06:00:00        100   comp1
759 2015-09-10 06:00:00        100   comp1
760 2015-12-09 06:00:00        100   comp2

[761 rows x 3 columns]

In [ ]:
df_errors

                datetime  machineID errorID
0    2015-01-03 07:00:00          1  error1
1    2015-01-03 20:00:00          1  error3
2    2015-01-04 06:00:00          1  error5
3    2015-01-10 15:00:00          1  error4
4    2015-01-22 10:00:00          1  error4
...                  ...        ...     ...
3914 2015-11-21 08:00:00        100  error2
3915 2015-12-04 02:00:00        100  error1
3916 2015-12-08 06:00:00        100  error2
3917 2015-12-08 06:00:00        100  error3
3918 2015-12-22 03:00:00        100  error3

[3919 rows x 3 columns]

In [ ]:
df_maint

                datetime  machineID   comp
0    2014-06-01 06:00:00          1  comp2
1    2014-07-16 06:00:00          1  comp4
2    2014-07-31 06:00:00          1  comp3
3    2014-12-13 06:00:00          1  comp1
4    2015-01-05 06:00:00          1  comp4
...                  ...        ...    ...
3281 2015-10-10 06:00:00        100  comp3
3282 2015-10-25 06:00:00        100  comp4
3283 2015-11-09 06:00:00        100  comp4
3284 2015-12-09 06:00:00        100  comp2
3285 2015-12-24 06:00:00        100  comp2

[3286 rows x 3 columns]

In [ ]:
# Merge telemetry data with machine features
df_combined = pd.merge(df_telemetry, df_machines, on='machineID', how='left')

# Merge with failures data (note: failures are sparse, so a left merge will introduce NaNs where no failure occurred)
df_combined = pd.merge(df_combined, df_failures, on=['datetime', 'machineID'], how='left')

# Merge with errors data
df_combined = pd.merge(df_combined, df_errors, on=['datetime', 'machineID'], how='left')

# Merge with maintenance data
df_combined = pd.merge(df_combined, df_maint, on=['datetime', 'machineID'], how='left')

print("All datasets merged.")
display(df_combined)

All datasets merged.

,datetime,machineID,volt,rotate,pressure,vibration,model,age,failure,errorID,comp
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686,model3,18,NaN,NaN,NaN
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973,model3,18,NaN,NaN,NaN
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847,model3,18,NaN,NaN,NaN
3,2015-01-01 09:00:00,1,162.462833,346.149335,109.248561,41.122144,model3,18,NaN,NaN,NaN
4,2015-01-01 10:00:00,1,157.610021,435.376873,111.886648,25.990511,model3,18,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
11591,2015-04-28 11:00:00,2,177.347926,457.666367,94.690314,39.253790,model4,7,NaN,NaN,NaN
11592,2015-04-28 12:00:00,2,160.741738,499.917353,102.990673,40.532562,model4,7,NaN,NaN,NaN
11593,2015-04-28 13:00:00,2,188.393731,489.567225,84.165825,40.536561,model4,7,NaN,NaN,NaN
11594,2015-04-28 14:00:00,2,195.562651,485.525334,102.696885,40.800559,model4,7,NaN,NaN,NaN
11595,2015-04-28 15:00:00,2,177.577279,528.590666,100.944514,47.150000,model4,7,NaN,NaN,NaN

Checking for Unique Classes in Dataset

In [ ]:
# Check unique classes and value counts for failure, errorID, and comp
categorical_cols = ['failure', 'errorID', 'comp']

for col in categorical_cols:
    print(f"--- Unique values in '{col}' ---")
    print(df_combined[col].value_counts(dropna=False))
    print("\n")

--- Unique values in 'failure' ---
failure
NaN      11580
comp4        7
comp2        6
comp1        3
Name: count, dtype: int64


--- Unique values in 'errorID' ---
errorID
NaN       11550
error1       13
error3       12
error2       10
error4        7
error5        4
Name: count, dtype: int64


--- Unique values in 'comp' ---
comp
NaN      11553
comp1       12
comp2       11
comp4       10
comp3       10
Name: count, dtype: int64

Combining 'failure' & 'comp' into 'comp_failure'

This is due to failure and comp having the same classes and in the original dataset for comp under 'maint', records are logged due to reactive or proactive maintenance. This means the assumption can be made that this is the recommended timing for maintenance/when the machine will break down. Hence, to play safe it is assumed as the moment when the machine will likely break down.

In [ ]:
# Combine 'comp' and 'failure' into a single column 'comp_failure'
# If one is NaN and the other has a value, it uses the non-NaN value.
# If both are NaN, it stays NaN.
df_combined['comp_failure'] = df_combined['failure'].combine_first(df_combined['comp'])

# Verify the result and check value counts
print(df_combined['comp_failure'].value_counts(dropna=False))

# Drop 'failure' and 'comp' columns in place
df_combined.drop(columns=['failure', 'comp'], inplace=True)

# Verify remaining columns
print(df_combined.columns)

comp_failure
NaN      11553
comp4       12
comp2       12
comp3       10
comp1        9
Name: count, dtype: int64
Index(['datetime', 'machineID', 'volt', 'rotate', 'pressure', 'vibration',
       'model', 'age', 'errorID', 'comp_failure'],
      dtype='object')

In [ ]:
# Filter rows where comp_failure is NaN AND errorID is NOT NaN
df_filtered = df_combined[df_combined['comp_failure'].isna() & df_combined['errorID'].notna()]

# Display the filtered DataFrame
display(df_filtered)

# Check the count of such rows
print(f"Number of matching rows: {len(df_filtered)}")

,datetime,machineID,volt,rotate,pressure,vibration,model,age,errorID,comp_failure
49,2015-01-03 07:00:00,1,175.213280,486.494804,104.432962,47.875804,model3,18,error1,NaN
62,2015-01-03 20:00:00,1,163.783704,520.582694,97.160984,56.442488,model3,18,error3,NaN
72,2015-01-04 06:00:00,1,165.010140,448.468838,97.709630,48.238941,model3,18,error5,NaN
226,2015-01-10 15:00:00,1,159.251350,462.691198,108.232985,31.200028,model3,18,error4,NaN
510,2015-01-22 10:00:00,1,152.789008,448.457864,98.709506,33.642445,model3,18,error4,NaN
587,2015-01-25 15:00:00,1,161.127404,371.685991,92.697430,52.362266,model3,18,error4,NaN
624,2015-01-27 04:00:00,1,203.200570,461.231784,92.790393,43.584343,model3,18,error1,NaN
1483,2015-03-03 22:00:00,1,175.887891,578.744306,106.216308,46.135737,model3,18,error2,NaN
1515,2015-03-05 06:00:00,1,208.701202,383.992489,103.683080,42.557824,model3,18,error1,NaN
1887,2015-03-20 18:00:00,1,169.489495,433.499388,100.824837,39.756476,model3,18,error1,NaN
2014,2015-03-26 01:00:00,1,132.556198,398.425464,81.024930,36.907715,model3,18,error2,NaN
2156,2015-03-31 23:00:00,1,187.069308,487.601113,97.837393,39.651108,model3,18,error1,NaN
2595,2015-04-19 06:00:00,1,156.765379,380.849889,94.354998,37.436059,model3,18,error2,NaN
2596,2015-04-19 06:00:00,1,156.765379,380.849889,94.354998,37.436059,model3,18,error3,NaN
2849,2015-04-29 19:00:00,1,157.009080,423.594032,105.120910,43.194925,model3,18,error4,NaN
2973,2015-05-04 23:00:00,1,178.861881,429.838659,104.605446,41.524197,model3,18,error2,NaN
3152,2015-05-12 09:00:00,1,184.525984,387.858303,70.233272,39.880788,model3,18,error1,NaN
3366,2015-05-21 07:00:00,1,162.868983,446.558268,101.776344,42.484768,model3,18,error4,NaN
3433,2015-05-24 02:00:00,1,158.663437,377.142519,88.340368,42.595978,model3,18,error3,NaN
3460,2015-05-25 05:00:00,1,178.250711,475.598298,99.432654,47.543946,model3,18,error1,NaN
3821,2015-06-09 06:00:00,1,165.711923,342.651084,91.085709,37.059634,model3,18,error3,NaN
4037,2015-06-18 06:00:00,1,167.428048,443.082952,96.968145,51.105583,model3,18,error5,NaN
4162,2015-06-23 10:00:00,1,178.887159,460.882621,107.236821,35.429333,model3,18,error3,NaN
5635,2015-08-23 19:00:00,1,155.368908,451.703227,104.793758,40.760926,model3,18,error1,NaN
5785,2015-08-30 01:00:00,1,171.416942,488.475353,110.409055,37.391164,model3,18,error3,NaN
5838,2015-09-01 06:00:00,1,188.464713,433.273533,121.728619,46.192763,model3,18,error5,NaN
6138,2015-09-13 17:00:00,1,186.459345,441.695821,83.362903,44.840679,model3,18,error2,NaN
6175,2015-09-15 06:00:00,1,171.255336,427.785145,110.032979,41.978642,model3,18,error1,NaN
6576,2015-10-01 23:00:00,1,155.591481,430.004526,133.374116,46.904855,model3,18,error1,NaN
6895,2015-10-15 05:00:00,1,140.082959,440.471289,102.243812,29.043994,model3,18,error1,NaN
6917,2015-10-16 03:00:00,1,172.210469,301.664587,107.243063,38.276014,model3,18,error3,NaN
6920,2015-10-16 06:00:00,1,203.130813,304.774518,101.433608,39.833376,model3,18,error2,NaN
6921,2015-10-16 06:00:00,1,203.130813,304.774518,101.433608,39.833376,model3,18,error3,NaN
7521,2015-11-10 04:00:00,1,195.053378,390.588385,96.913999,32.404521,model3,18,error3,NaN
8363,2015-12-15 06:00:00,1,181.399934,402.527210,107.692113,50.295324,model3,18,error5,NaN
9044,2015-01-12 14:00:00,2,181.303936,477.919565,101.761350,39.881943,model4,7,error4,NaN
9640,2015-02-06 10:00:00,2,175.632818,415.058978,77.985815,35.661158,model4,7,error4,NaN
9761,2015-02-11 11:00:00,2,149.859204,450.107091,122.418299,41.058270,model4,7,error1,NaN
10444,2015-03-11 22:00:00,2,131.659284,490.607915,106.405936,43.380925,model4,7,error2,NaN
10596,2015-03-18 06:00:00,2,168.448450,358.743487,89.573491,34.848273,model4,7,error1,NaN
10597,2015-03-18 06:00:00,2,168.448450,358.743487,89.573491,34.848273,model4,7,error2,NaN
10598,2015-03-18 06:00:00,2,168.448450,358.743487,89.573491,34.848273,model4,7,error3,NaN
10790,2015-03-26 03:00:00,2,155.506049,356.823930,111.000158,37.377899,model4,7,error2,NaN
10828,2015-03-27 17:00:00,2,188.900663,560.334587,94.443209,42.877805,model4,7,error3,NaN
11321,2015-04-17 06:00:00,2,170.717684,333.297871,90.376027,43.135057,model4,7,error2,NaN
11322,2015-04-17 06:00:00,2,170.717684,333.297871,90.376027,43.135057,model4,7,error3,NaN

Number of matching rows: 46

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import pandas as pd

# 1. Features to use for prediction
feature_cols = ['volt', 'rotate', 'pressure', 'vibration', 'model', 'age']

# Preprocess features (One-Hot Encoding & Scaling)
X_all = pd.get_dummies(df_combined[feature_cols], columns=['model'], drop_first=True)
scaler = StandardScaler()
X_scaled = pd.DataFrame(scaler.fit_transform(X_all), index=df_combined.index)

# 2. Define masks for training and target sets
# Train set: Rows where comp_failure is already known
train_mask = df_combined['comp_failure'].notna()

# Target set: Rows where comp_failure is NaN BUT errorID is present
target_mask = df_combined['comp_failure'].isna() & df_combined['errorID'].notna()

# Extract train and target data
X_train = X_scaled[train_mask]
y_train = df_combined.loc[train_mask, 'comp_failure']

X_target = X_scaled[target_mask]

# 3. Fit KNN Classifier on known cases only and predict target cases
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

predicted_comps = knn.predict(X_target)

# 4. Fill in the imputed values for the target rows only
df_combined.loc[target_mask, 'comp_failure'] = predicted_comps

# Update 'failed' indicator column accordingly
df_combined['failed'] = df_combined['comp_failure'].notna().astype(int)

# Verify the updated class distribution
print("--- Updated comp_failure value counts ---")
print(df_combined['comp_failure'].value_counts(dropna=False))

--- Updated comp_failure value counts ---
comp_failure
NaN      11507
comp2       29
comp1       22
comp4       20
comp3       18
Name: count, dtype: int64

In [ ]:
# Create 'failed' column: 1 if comp_failure is not NaN, else 0
df_combined['failed'] = df_combined['comp_failure'].notna().astype(int)

# Verify the changes and check class distribution
print(df_combined['failed'].value_counts(dropna=False))

failed
0    11507
1       89
Name: count, dtype: int64

In [ ]:
# Save to Colab session storage
df_combined.to_csv('df_combined.csv', index=False)
print("Saved df_combined.csv successfully!")

Saved df_combined.csv successfully!

### Feature Engineer

Read Combined CSV File

In [ ]:
df_combined = pd.read_csv('/content/df_combined.csv')

In [ ]:
df_combined

,datetime,machineID,volt,rotate,pressure,vibration,model,age,errorID,comp_failure,failed
0,2015-01-01 06:00:00,1,176.217853,418.504078,113.077935,45.087686,model3,18,NaN,NaN,0
1,2015-01-01 07:00:00,1,162.879223,402.747490,95.460525,43.413973,model3,18,NaN,NaN,0
2,2015-01-01 08:00:00,1,170.989902,527.349825,75.237905,34.178847,model3,18,NaN,NaN,0
3,2015-01-01 09:00:00,1,162.462833,346.149335,109.248561,41.122144,model3,18,NaN,NaN,0
4,2015-01-01 10:00:00,1,157.610021,435.376873,111.886648,25.990511,model3,18,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
11591,2015-04-28 11:00:00,2,177.347926,457.666367,94.690314,39.253790,model4,7,NaN,NaN,0
11592,2015-04-28 12:00:00,2,160.741738,499.917353,102.990673,40.532562,model4,7,NaN,NaN,0
11593,2015-04-28 13:00:00,2,188.393731,489.567225,84.165825,40.536561,model4,7,NaN,NaN,0
11594,2015-04-28 14:00:00,2,195.562651,485.525334,102.696885,40.800559,model4,7,NaN,NaN,0
11595,2015-04-28 15:00:00,2,177.577279,528.590666,100.944514,47.150000,model4,7,NaN,NaN,0

In [ ]:
# 1. Drop 'machineID'
df_combined = df_combined.drop(columns=['machineID'])

# 2. Apply One-Hot Encoding to categorical columns
# Note: dummy_na=False (default) keeps NaNs as all zeros in OHE columns.
# Set dummy_na=True if you want explicit columns for NaN values.
df_combined = pd.get_dummies(
    df_combined,
    columns=['model', 'errorID', 'comp_failure'],
    dtype=int,  # Outputs 1/0 instead of True/False
)

# Display the updated DataFrame shape and new columns
print(f"New DataFrame shape: {df_combined.shape}")
df_combined.head()

New DataFrame shape: (11596, 18)

,datetime,volt,rotate,pressure,vibration,age,failed,model_model3,model_model4,errorID_error1,errorID_error2,errorID_error3,errorID_error4,errorID_error5,comp_failure_comp1,comp_failure_comp2,comp_failure_comp3,comp_failure_comp4
0,2015-01-01 06:00:00,176.217853,418.504078,113.077935,45.087686,18,0,1,0,0,0,0,0,0,0,0,0,0
1,2015-01-01 07:00:00,162.879223,402.747490,95.460525,43.413973,18,0,1,0,0,0,0,0,0,0,0,0,0
2,2015-01-01 08:00:00,170.989902,527.349825,75.237905,34.178847,18,0,1,0,0,0,0,0,0,0,0,0,0
3,2015-01-01 09:00:00,162.462833,346.149335,109.248561,41.122144,18,0,1,0,0,0,0,0,0,0,0,0,0
4,2015-01-01 10:00:00,157.610021,435.376873,111.886648,25.990511,18,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Save to Colab session storage
df_combined.to_csv('model_dataset.csv', index=False)
print("Saved model_dataset.csv successfully!")

Saved model_dataset.csv successfully!

### Model Training

Please note image and numerical data here are using testing synthetic data

Libraries & Seed

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import torchvision.models as models
import numpy as np
from sklearn.metrics import precision_recall_curve, auc, f1_score, precision_score, recall_score

# Set seed for reproducibility
torch.manual_seed(42)
np.random.seed(42)

In [ ]:
# ==========================================
# 1. TEMPORAL-AWARE RESAMPLING & DATASET
# ==========================================

class MultimodalMaintenanceDataset(Dataset):
    """
    Sequence-level sliding window dataset with time-series, numerical features, and images.
    """
    def __init__(self, num_samples=1000, sequence_length=64, img_size=(3, 64, 64), failure_rate=0.05):
        self.sequence_length = sequence_length
        self.num_samples = num_samples

        # Simulate tabular numerical features (e.g., machine age, static spec embeddings)
        self.numerical_data = np.random.randn(num_samples, 5).astype(np.float32)

        # Simulate time-series sensor data (e.g., volt, rotate, pressure, vibration)
        self.timeseries_data = np.random.randn(num_samples, sequence_length, 4).astype(np.float32)

        # Simulate visual data (e.g., thermal/visual frame sequence or summary image per window)
        self.image_data = np.random.randn(num_samples, img_size[0], img_size[1], img_size[2]).astype(np.float32)

        # Simulate highly imbalanced labels (1 = failure in window, 0 = normal)
        self.labels = np.random.choice([0, 1], size=num_samples, p=[1 - failure_rate, failure_rate])

        # Simulate Time-to-Failure (TTF) in hours (e.g., 0 to 72 hours window for failures)
        self.ttf_targets = np.where(self.labels == 1, np.random.uniform(1.0, 72.0, size=num_samples), 168.0).astype(np.float32)

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return {
            'ts': torch.tensor(self.timeseries_data[idx]),
            'num': torch.tensor(self.numerical_data[idx]),
            'img': torch.tensor(self.image_data[idx]),
            'label': torch.tensor(self.labels[idx], dtype=torch.float32),
            'ttf': torch.tensor(self.ttf_targets[idx], dtype=torch.float32)
        }

def build_oversampled_dataloader(dataset, batch_size=32):
    """
    Sequence-level oversampling using WeightedRandomSampler to address class imbalance.
    """
    labels = dataset.labels
    class_counts = np.bincount(labels)
    class_weights = 1.0 / class_counts
    sample_weights = class_weights[labels]

    sampler = WeightedRandomSampler(
        weights=torch.DoubleTensor(sample_weights),
        num_samples=len(sample_weights),
        replacement=True
    )

    return DataLoader(dataset, batch_size=batch_size, sampler=sampler)

In [ ]:
# ==========================================
# 2. STREAMING MULTIMODAL TRANSFORMER (StreaMulT)
# ==========================================

class StreamingMultimodalTransformer(nn.Module):
    def __init__(self, ts_features=4, num_features=5, embed_dim=64, nhead=4, num_layers=2):
        super().__init__()

        # 1. Modality Encoders
        # Time-Series Projection
        self.ts_projection = nn.Linear(ts_features, embed_dim)

        # Tabular Numerical Projection
        self.num_projection = nn.Sequential(
            nn.Linear(num_features, embed_dim),
            nn.ReLU(),
            nn.Linear(embed_dim, embed_dim)
        )

        # Vision Encoder (CNN Backing)
        resnet = models.resnet18(weights=None)
        resnet.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3, bias=False)
        self.img_encoder = nn.Sequential(*list(resnet.children())[:-1]) # Extract features before FC
        self.img_projection = nn.Linear(resnet.fc.in_features, embed_dim)

        # 2. Cross-Modal Fusion Transformer Engine
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=nhead,
            dim_feedforward=embed_dim * 2,
            batch_first=True
        )
        self.transformer_fusion = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # 3. Multitask Prediction Heads
        # Task A: Binary Classification Probability Head (Failure Likelihood)
        self.classifier_head = nn.Sequential(
            nn.Linear(embed_dim, 32),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(32, 1) # Outputs logits
        )

        # Task B: Remaining Useful Life / Time-To-Failure Head (Regression in Hours)
        self.rul_head = nn.Sequential(
            nn.Linear(embed_dim, 32),
            nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, ts, num, img):
        # Shape prep
        batch_size, seq_len, _ = ts.shape

        # Project Time-Series: [B, T, D]
        ts_emb = self.ts_projection(ts)

        # Project Tabular Numerical: [B, 1, D]
        num_emb = self.num_projection(num).unsqueeze(1)

        # Extract Visual Feature Embeddings: [B, 1, D]
        img_feat = self.img_encoder(img).squeeze(-1).squeeze(-1)
        img_emb = self.img_projection(img_feat).unsqueeze(1)

        # Cross-Modal Fusion Sequence Concatenation: [B, (T + 1 + 1), D]
        fused_sequence = torch.cat([ts_emb, num_emb, img_emb], dim=1)

        # Transformer Encoding
        transformer_out = self.transformer_fusion(fused_sequence)

        # Pooling sequence representation (mean pooling over temporal-modal tokens)
        pooled = transformer_out.mean(dim=1)

        # Multi-task Outputs
        failure_logits = self.classifier_head(pooled).squeeze(-1)
        ttf_pred = F.relu(self.rul_head(pooled).squeeze(-1)) # Positive hours constraint

        return failure_logits, ttf_pred

In [ ]:
# ==========================================
# 3. TRAINING & LOSS STRATEGY
# ==========================================

def train_model():
    # Setup dataset & sampler dataloader
    dataset = MultimodalMaintenanceDataset(num_samples=1200, sequence_length=64, failure_rate=0.08)
    dataloader = build_oversampled_dataloader(dataset, batch_size=32)

    model = StreamingMultimodalTransformer()

    # Weighted Cross Entropy strategy for class imbalance
    # Calculate pos_weight = negative_class_count / positive_class_count
    num_positives = sum(dataset.labels)
    num_negatives = len(dataset.labels) - num_positives
    pos_weight = torch.tensor([num_negatives / max(num_positives, 1)])

    cls_criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
    rul_criterion = nn.MSELoss()

    optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3, weight_decay=1e-4)

    model.train()
    print("Beginning Training...")
    for epoch in range(3):
        total_loss = 0.0
        for batch in dataloader:
            optimizer.zero_grad()

            logits, ttf_pred = model(batch['ts'], batch['num'], batch['img'])

            # Loss computation
            cls_loss = cls_criterion(logits, batch['label'])
            rul_loss = rul_criterion(ttf_pred, batch['ttf'])

            # Joint multi-task loss balance
            loss = cls_loss + 0.01 * rul_loss
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}/3 - Loss: {total_loss / len(dataloader):.4f}")

    return model, dataset

In [ ]:
# ==========================================
# 4. POST-TRAINING THRESHOLD TUNING & METRICS
# ==========================================

def evaluate_and_tune(model, dataset):
    model.eval()
    val_loader = DataLoader(dataset, batch_size=64, shuffle=False)

    all_targets = []
    all_probs = []
    all_ttfs = []

    with torch.no_grad():
        for batch in val_loader:
            logits, ttf_pred = model(batch['ts'], batch['num'], batch['img'])
            probs = torch.sigmoid(logits)

            all_probs.extend(probs.numpy())
            all_targets.extend(batch['label'].numpy())
            all_ttfs.extend(ttf_pred.numpy())

    all_probs = np.array(all_probs)
    all_targets = np.array(all_targets)
    all_ttfs = np.array(all_ttfs)

    # Calculate Precision-Recall AUC
    precision, recall, thresholds = precision_recall_curve(all_targets, all_probs)
    pr_auc = auc(recall, precision)

    # Threshold Tuning: Finding the optimal decision threshold for F1-Score
    f1_scores = [2 * (p * r) / (p + r + 1e-10) for p, r in zip(precision, recall)]
    best_idx = np.argmax(f1_scores)

    # If best_idx falls out of range of thresholds array:
    optimal_threshold = thresholds[best_idx] if best_idx < len(thresholds) else 0.5
    best_f1 = f1_scores[best_idx]

    # Evaluate at optimal threshold
    predictions = (all_probs >= optimal_threshold).astype(int)
    tuned_precision = precision_score(all_targets, predictions, zero_division=0)
    tuned_recall = recall_score(all_targets, predictions, zero_division=0)

    print("\n" + "="*45)
    print("         EVALUATION & THRESHOLD RESULTS       ")
    print("="*45)
    print(f"PR-AUC (Average Precision) : {pr_auc:.4f}")
    print(f"Optimal Probability Threshold: {optimal_threshold:.4f}")
    print(f"F1-Score at Threshold      : {best_f1:.4f}")
    print(f"Precision at Threshold     : {tuned_precision:.4f}")
    print(f"Recall at Threshold        : {tuned_recall:.4f}")
    print("="*45)

    # Sample Output Inference Prediction
    sample_idx = 0
    print("\n[SAMPLE INFERENCE OUTPUT]")
    print(f"Predicted Probability of Failure : {all_probs[sample_idx]*100:.2f}%")
    print(f"Tuned Failure Alert Binary      : {'ALERT: FAILURE IMMINENT' if all_probs[sample_idx] >= optimal_threshold else 'NORMAL'}")
    print(f"Predicted Time-To-Failure (TTF) : {all_ttfs[sample_idx]:.2f} Hours")

# Execute Pipeline
if __name__ == "__main__":
    trained_model, val_dataset = train_model()
    evaluate_and_tune(trained_model, val_dataset)

Beginning Training...
Epoch 1/3 - Loss: 149.9619
Epoch 2/3 - Loss: 139.4047
Epoch 3/3 - Loss: 116.3805

=============================================
         EVALUATION & THRESHOLD RESULTS
=============================================
PR-AUC (Average Precision) : 0.9577
Optimal Probability Threshold: 0.9893
F1-Score at Threshold      : 0.9158
Precision at Threshold     : 0.9457
Recall at Threshold        : 0.8878
=============================================

[SAMPLE INFERENCE OUTPUT]
Predicted Probability of Failure : 73.13%
Tuned Failure Alert Binary      : NORMAL
Predicted Time-To-Failure (TTF) : 24.34 Hours

In [ ]:
# 1. Select a random sample index from the validation dataset
random_idx = np.random.randint(0, len(val_dataset))

# 2. Extract the sample data
sample = val_dataset[random_idx]
ts_data = sample["ts"].unsqueeze(0)  # Add batch dimension [1, seq_len, ts_features]
num_data = sample["num"].unsqueeze(0)  # Add batch dimension [1, num_features]
img_data = sample["img"].unsqueeze(0)  # Add batch dimension [1, C, H, W]
true_label = int(sample["label"].item())
true_ttf = sample["ttf"].item()

# 3. Run inference with the trained model
trained_model.eval()
with torch.no_grad():
    logit, ttf_pred = trained_model(ts_data, num_data, img_data)
    prob = torch.sigmoid(logit).item()
    pred_ttf = ttf_pred.item()

# Assuming 'optimal_threshold' from your evaluation function (e.g., 0.9893)
# Fallback to 0.5 if not previously defined in global scope
threshold = optimal_threshold if "optimal_threshold" in locals() else 0.5
alert_status = "ALERT: FAILURE IMMINENT" if prob >= threshold else "NORMAL"

# 4. Display the selected input row and prediction results
print("=" * 55)
print(f"         RANDOM VALIDATION ROW TEST (Index: {random_idx})")
print("=" * 55)

print("\n--- INPUT DATA FEATURES ---")
print(
    f"Numerical Features (Age/Specs) : {num_data.squeeze(0).numpy().tolist()}"
)
print(
    f"Time-Series Shape (Sensors)    : {ts_data.squeeze(0).shape} (Last step: {ts_data[0, -1].numpy().round(2).tolist()})"
)
print(f"Image Tensor Shape             : {img_data.squeeze(0).shape}")

print("\n--- GROUND TRUTH ---")
print(f"Actual Failure Label           : {true_label}")
print(f"Actual Time-To-Failure (TTF)   : {true_ttf:.2f} Hours")

print("\n--- MODEL PREDICTION ---")
print(f"Predicted Failure Probability  : {prob * 100:.2f}%")
print(f"Tuned Failure Alert Binary     : {alert_status}")
print(f"Predicted Time-To-Failure (TTF): {pred_ttf:.2f} Hours")
print("=" * 55)

=======================================================
         RANDOM VALIDATION ROW TEST (Index: 413)
=======================================================

--- INPUT DATA FEATURES ---
Numerical Features (Age/Specs) : [-0.5827586650848389, -2.438817262649536, -0.13427916169166565, 1.42274808883667, 0.926215410232544]
Time-Series Shape (Sensors)    : torch.Size([64, 4]) (Last step: [1.649999976158142, -0.25999999046325684, 3.259999990463257, 0.6600000262260437])
Image Tensor Shape             : torch.Size([3, 64, 64])

--- GROUND TRUTH ---
Actual Failure Label           : 1
Actual Time-To-Failure (TTF)   : 27.71 Hours

--- MODEL PREDICTION ---
Predicted Failure Probability  : 98.99%
Tuned Failure Alert Binary     : ALERT: FAILURE IMMINENT
Predicted Time-To-Failure (TTF): 22.31 Hours
=======================================================